# Generated by Django 4.0.4 on 2022-05-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=50)),
                ('original_id', models.BigIntegerField(db_index=True, unique=True)),
                ('quantity', models.CharField(max_length=30)),
                ('keywords', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('image_thumb_url', models.URLField()),
                ('nutriscore_grade', models.CharField(max_length=2)),
                ('ingredients_text', models.TextField()),
                ('stores', models.TextField()),
                ('nutriments', models.JSONField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='L_Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_products', to='products.product')),
                ('substitue_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substite_products', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('products', models.ManyToManyField(related_name='categories', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
