# Generated by Django 4.0.3 on 2022-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Licenciement', 'Customer'), ('Gel des embauches', 'Admin')], default='Licenciement', max_length=30),
        ),
    ]
