# Generated by Django 4.0.3 on 2022-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Customer'), ('administrateur', 'Admin')], default='client', max_length=30),
        ),
    ]
