# Generated by Django 4.0.3 on 2022-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Client', 'Customer'), ('Client Premium', 'Premium Customer'), ('VIP', 'Vip')], default='Client', max_length=30),
        ),
    ]
